server.port=8084
spring.application.name=interview-hub

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://35.244.60.117:5432/mydb?sslmode=disable&sslfactory=org.postgresql.ssl.NonValidatingFactory&preferQueryMode=simple
spring.datasource.username=postgres
spring.datasource.password=Mydb1298@
spring.datasource.hikari.allow-pool-suspension=true
spring.datasource.hikari.autoCommit=true
spring.datasource.driver-class-name=org.postgresql.Driver

# Schema Initialization
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:schema-postgres.sql
#spring.jpa.hibernate.ddl-auto=none


# Connection Pool Configuration
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# Additional PostgreSQL Configuration
spring.datasource.hikari.connectionTestQuery=SELECT 1
spring.datasource.hikari.validation-timeout=5000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
