server.port=8084
spring.application.name=interview-hub

# --- PostgreSQL DB Connection ---
spring.datasource.url=jdbc:postgresql://34.93.247.87:5432/postgres?sslmode=disable&sslfactory=org.postgresql.ssl.NonValidatingFactory&preferQueryMode=simple
# spring.datasource.url=jdbc:postgresql://35.244.60.117:5432/mydb?sslmode=disable&sslfactory=org.postgresql.ssl.NonValidatingFactory&preferQueryMode=simple
spring.datasource.username=postgres
spring.datasource.password=Pawan@123
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HikariCP Connection Pool ---
spring.datasource.hikari.pool-name=InterviewHubHikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000       
spring.datasource.hikari.max-lifetime=600000       
spring.datasource.hikari.connection-timeout=20000 
spring.datasource.hikari.keepalive-time=300000    
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.allow-pool-suspension=true

# --- Hibernate/JPA ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=false
spring.jpa.open-in-view=false
